# Biomass {#cha:biomass}



## Biomass accumulation (Photosynthesis)

```{block type='rmdimportant', echo=TRUE}
This section is directly copied from documentation of APSIM-Wheat 7.5. All details need to be checked for the APSIM next generation. 
```

The daily biomass accumulation ($\Delta Q$) corresponds to dry-matter above-ground biomass, and is calculated as a potential biomass accumulation resulting from radiation interception ($\Delta Q_{r}$) that is limited by soil water deficiency ($\Delta Q_{w}$).

### Potential biomass accumulation from radiation use efficiency


The radiation-limited dry-biomass accumulation ($\Delta Q_{r}$) is calculated by the intercepted radiation ($I$), radiation use efficiency ($RUE$), diffuse factor ($f_{d}$), stress factor ($f_{s}$) and carbon dioxide factor ($f_{c}$).

$$\Delta Q_{r}=I\times RUE\times f_{d}\times f_{s}\times f_{c}\label{eq:BiomassProduction}$$

where $f_{d}$, $f_{s}$ and $f_{c}$ are defined in the wheat.xml file. In the current version of APSIM-Wheat, only `Leaf` produces photosynthate. Diffuse factor ($f_{d}$) equals to 1 (), so that can be: $$\Delta Q_{r}=I\times RUE\times f_{s}\times f_{c}\label{eq:BiomassProduction2}$$

### Radiation interception

Radiation interception is calculated from the leaf area index (LAI, m$^{2}$ m$^{-2}$) and the extinction coefficient (*k*) [@monsi2005onthe]. $$I=I_{0}(1-\exp(-k\times LAI\times f_{h})/f_{h})\label{eq:RadiationInterception}$$ where $I_{0}$ is the total radiation at the top of the canopy (MJ) which is directly imported from weather records; $f_{h}$ is light interception modified to give hedge-row effect with skip row. $f_{h}$ could be calculated based on the canopy width, but is not used in the current version of APSIM (i.e. $f_{h}$ = 1). So, is reduced to. $$I=I_{0}(1-\exp(-k\times LAI))\label{eq:RadiationInterception-1}$$

Extinction coefficient ($k$) varies with row spacing, $$k=h_{e}(W_{r})$$ where $W_{r}$ is the row spacing which is specified by the user (in the APSIM interface, the .sim or .apsim file); $h_{e}$ is a function of rowing spacing which is defined for both green leaf and dead leaves by parameters `x_row_spacing`, `y_extinct_coef` in the wheat.xml file () and is linearly interpolated by APSIM. In the current version of APSIM-Wheat, no impact of row spacing is considered ()

### Radiation use efficiency

$RUE$ (g MJ$^{\text{-1}}$) is a function of growth stages which is defined by parameters `x_stage_rue` and `y_rue` in wheat.xml () and linearly interpolated by APSIM. In the current version of APSIM-Wheat, $RUE$ equal to 1.24 from emergence to the end of grain-filling and does not vary as a function of daily incident radiation as in the model NWHEAT.

### Stress factor (Temperature, nitrogen, phosphorus (not applied), oxygen (not applied))

Actual daily radiation-limited biomass accumulation can be reduced by a stress factor ($f_{s}$, and ). This stress factor is the minimum value of a temperature factor ($f_{T,\ photo}$), a nitrogen factor ($f_{N\ photo}$), a phosphorus factor ($f_{P\ photo}$) and an oxygen factor ($f_{O\ photo}$). $$f_{s}=\min(f_{T,\ photo},\ f_{N,\ photo},\ f_{P,\ photo},\ f_{O,\ photo})\label{eq:StressFactor4Photosynthesis}$$ No phosphorus stress $f_{P,\,photo}$ and oxygen stress $f_{O,\,photo}$ are applied in the current version of APSIM-Wheat. So, is reduced to $$f_{s}=\min(f_{T,\ photo},\ f_{N,\ photo})\label{eq:StressFactor4Photosynthesis2}$$

#### The temperature factor

$f_{T,\ photo}$ is a function of the daily mean temperature and is defined by parameters `x_ave_temp` and `y_stress_photo` in the wheat.xml (). Values are linearly interpolated by APSIM. The temperature stress is applied from sowing to harvest.

$$f_{T,\ photo}=h_{T,\ photo}(\frac{T_{max}+T_{min}}{2})\label{eq:TemStressPhoto}$$

#### The nitrogen factor

$f_{N,\,photo}$ is determined by the difference between leaf nitrogen concentration and leaf minimum and critical nitrogen concentration.

$$f_{N,\,photo}=R_{N,\,photo}\sum_{leaf}\frac{C_{N}-C_{N,\,min}}{C_{N,\,crit}-C_{N,\,min}}\label{eq:NStressPhoto0}$$

where $C_{N}$ is the nitrogen concentration of `Leaf` parts; $R_{N,\,expan}$ is multiplier for nitrogen deficit effect on phenology which is specified by `N_fact_photo` in the wheat.xml and default value is 1.5.

#### The CO$_{\text{2}}$ factor

For C3 plants (like wheat), the CO$_{\text{2}}$ factor of APSIM is calculated by a function of environmental CO$_{\text{2}}$ concentration ($C$, ppm) and daily mean temperature ($T_{mean}$) as published by @reyenga1999modelling

$$f_{c}=\frac{(C-C_{i})(350+2C_{i})}{(C+2C_{i})(350-C_{i})}\label{eq:CO2Factor4Photosynthesis}$$

where $C_{i}$ is the temperature dependent CO$_{\text{2}}$ compensation point (ppm) and is derived from the following function. $$C_{i}=\frac{163-T_{mean}}{5-0.1T_{mean}}$$

#### Diffuse factor (not used in the current version)\[par:Diffuse-factor\]

The daily diffuse fraction was calculated using the functions suggested by @roderick1999estimating:

$$\begin{cases}
\frac{R_{d}}{R_{s}}=Y_{0} & \qquad for\:\frac{R_{s}}{R_{o}}\leq X_{0}\\
\frac{R_{d}}{R_{s}}=A_{0}+A_{1}\frac{R_{s}}{R_{o}} & \qquad for\:X_{0}<\frac{R_{s}}{R_{o}}\leq X_{1}\\
\frac{R_{d}}{R_{s}}=Y_{1} & \qquad for\:\frac{R_{s}}{R_{o}}>X_{1}
\end{cases}\label{eq:DiffuseFraction}$$

where $$\begin{array}{c}
A_{0}=Y_{1}-A_{1}X_{1}\\
A_{1}=\frac{Y_{1}-Y_{0}}{X_{1}-X_{0}}
\end{array}$$ where $R_{o}$ is the daily extra-terrestrial solar irradiance (i.e. top of the atmosphere); $R_{d}$ and $R_{s}$ are the daily diffuse and global solar irradiance at the surface, respectively. $X_{0}$, $X_{1}$, $Y_{0}$ and $Y_{1}$ are four empirical parameters. $$\begin{array}{l}
X_{0}=0.26,\qquad Y_{0}=0.96,\qquad Y_{1}=0.05,\;and\\
X_{1}=0.80-0.0017|\varphi|+0.000044|\varphi|^{2}
\end{array}$$ where $\varphi$ is latitude.

$R_{o}$ is derived from this function $$R_{0}=\frac{86400\times1360\times(\varpi\times\sin(\varphi)\times\sin(\theta)+\cos(\varphi)\times\cos(\theta)\times\sin(\varpi_{0}))}{1000000\pi}$$ where $\varpi_{0}$ is the time of sunrise and sunset, which derives from any solar declination ($\theta$) and latitude ($\varphi$) in terms of local solar time when sunrise and sunset actually occur (<http://en.wikipedia.org/wiki/Sunrise_equation>) $$\varpi_{0}=\arccos(-\tan(\varphi)\tan(\theta))$$ Solar declination ($\theta$) can be calculated by $$\theta=23.45\sin(\frac{2\pi}{365.25}(N-82.25))$$ where $N$ is day of year.

$f_{d}$ is calculated by a function of the diffuse fraction which is not implemented in current wheat module, (i.e. $f_{d}$ = 1).

### Actual daily biomass accumulation


The actual daily biomass accumulation ($\Delta Q$) results from water limitation applied on the potential radiation-driven biomass accumulation ($\Delta Q_{r}$). This water-limited biomass ($\Delta Q_{w}$) is a function of the ratio between the daily water uptake ($W_{u}$) and demand ($W_{d}$) capped by $$\Delta Q_{w}=\Delta Q_{r}f_{w,\,photo}=\Delta Q_{r}\frac{W_{u}}{W_{d}}\label{eq:WaterStressBiomassProduction-1}$$ where $f_{w,\,photo}$ is the water stress factor affecting photosynthesis (); $W_{u}$ is the actual daily water uptake from the root system (which corresponds to the soil water supply ($W_{s}$) capped by $W_{d}$), $W_{d}$ is the soil water demand of Leaf and Head parts ().

When the soil water is non-limiting ($f_{w,\,photo}$ = 1, i.e. $W_{d}\geq W_{s}$), biomass accumulation is limited by the radiation ($\Delta Q=\Delta Q_{r}$). When the soil water is limiting, biomass accumulation is limited by water supply ($\Delta Q=\Delta Q_{w}$).

The water demand ($W_{d}$, in mm) corresponds to the amount of water the crop would have transpired in the absence of soil water constraint, and is calculated from the potential biomass accumulation from RUE ($\Delta Q_{r}$). Following @sinclair1986waterand, transpiration demand is modeled as a function of the current day’s crop growth rate, estimated by the potential biomass accumulation associated with intercepted radiation ($\Delta Q_{r}$, see ), divided by the transpiration efficiency.

$$W_{d}=\frac{\Delta Q_{r}-R}{TE}\label{eq:soilWaterDemand-1}$$

where $R$ is respiration rate and equals to zero in the current version of APSIM-Wheat, $TE$ is transpiration efficiency (). See for more details about water demand and supply.

The daily biomass accumulation ($\Delta Q$) corresponds to dry matter above ground biomass is limited by the radiation interception ($\Delta Q_{r}$) or by soil water deficiency ($\Delta Q_{w}$), so that daily biomass accumulation can be expressed as: $$\Delta Q=\begin{cases}
\Delta Q_{r}\qquad & W_{u}=W_{d}\\
\Delta Q_{w}\qquad & W_{u}<W_{d}
\end{cases}\label{eq:actualBiomassProduction}$$ where $W_{s}$ is water supply, $W_{d}$ is the soil water demand from the shoot, limited by radiation interception (). In the current APSIM-Wheat, $W_{d}$ is actually only directly affected by the soil water demand of the leaf (). $W_{u}$ and $W_{d}$ are calculated by soil module of APSIM.



## Biomass partitioning

