# Leaf {#cha:leaf}


```{r setup_leaf, message=FALSE, echo=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(
    cache = TRUE, echo = FALSE, 
    out.width = '80%', fig.asp = .75,
    warning = FALSE, fig.align = 'center',
    message = FALSE) 
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(xml2)
library(DiagrammeR)
source('_utility.R')
report <- read_csv('process_test/simulation.db.Report.csv')

df <- report %>% 
    filter(grepl('15TraitMod', Name),
           Management == 'IHN',
           Cultivar == 'hartog')

pmf <- read_xml('process_test/simulation.apsimx')


x_var <- c(
    'Wheat.Phenology.Stage',
    'Wheat.Phenology.AccumulateThermalTime')
x_lab <- 'Accumulated thermal time, stage'
```



Leaf cohort model is used in the ...

## Life growth cycle

In the leaf cohort model, the leaf growth cycle is divided into 7 stages.

```{r leaf-life-cycle, out.width='100%'}
library(DiagrammeR)
DiagrammeR("sequenceDiagram;
	Initialized->>Appeared: Appearance 
	Appeared->>Expanded: GrowthDuration
	Expanded->>Senescing: LagDuration
	Senescing->>Senesced: SenescenceDuration
	Senesced->>Detaching: DetachmentLagDuration
	Detaching->>Detached: DetachmentDuration
	Initialized->Expanded: IsGrowing
	Initialized->>Senesced: IsAlive
	Initialized->>Senesced: IsGreen
	Initialized->>Senescing: IsNotSenescing
	Senescing->>Senesced: IsSenescing
	Expanded->>Detached: IsFullyExpanded
	Senesced->>Detached: ShouldBeDead
	Senesced->>Detached: Finished
	Appeared->>Detached: IsAppeared
	Initialized->>Detached: IsInitialised
")
```

## leaf age

The age of leaf...

```{block, type='rmdimportant', echo=TRUE}
The actual unit for PlantAppearedLeafNo is per square meter ([#842](https://github.com/APSIMInitiative/ApsimX/issues/842)).

```

<div class="fig-output">
```{r leaf-number, fig.asp = 1.3, fig.cap='Appeared number of green, senesced and total leaves'}
y_cols <- c(
    'Wheat.Leaf.PlantAppearedLeafNo',
    'Wheat.Leaf.PlantAppearedGreenLeafNo',
    'Wheat.Leaf.PlantsenescedLeafNo')

plot_report(df, x_var, y_cols, x_lab = x_lab, 
            y_lab = 'Leaf number')


```
</div>



<div class="fig-output">
```{r leaf-cohort-number, fig.asp = 1.4, fig.cap='Initialized, appeared and expanding cohort number'}
y_cols <- c(
            'Wheat.Leaf.ExpandingCohortNo',
            'Wheat.Leaf.InitialisedCohortNo',
            'Wheat.Leaf.AppearedCohortNo',
            'Wheat.Leaf.SenescingCohortNo',
            'Wheat.Leaf.DeadCohortNo')

plot_report(df, x_var, y_cols, x_lab = x_lab, 
            y_lab = 'Cohort number')


```
</div>



<div class="fig-output">
```{r leaf-age, fig.cap='Age of leaf cohort as a function of stage or accumulated thermal time', fig.subcap=c('A', 'B')}
y_cols <- c(
    'Wheat.Leaf.CohortAge')
plot_report_vector(
    df, x_var, y_cols, x_lab = x_lab, 
    y_lab = 'Age of leaf cohort')


```
</div>



<div class="fig-output">
```{r leaf-lai, fig.cap='Leaf area index', fig.subcap=c('Stage', 'Thermal time')}
y_cols <- c(
    'Wheat.Leaf.LAI', 
'Wheat.Leaf.LAIDead',
'Wheat.Leaf.LAITotal')
plot_report(df, x_var, y_cols, x_lab = x_lab, y_lab = 'Leaf area index')

```
</div>


<div class="fig-output">
```{r leaf-cover, fig.cap='Coverage', fig.subcap=c('Stage', 'Thermal time')}
y_cols <- c(
    'Wheat.Leaf.CoverGreen',
    'Wheat.Leaf.CoverDead',
    'Wheat.Leaf.CoverTotal')
plot_report(df, x_var, y_cols, x_lab = x_lab, y_lab = 'Coverage')

```
</div>





