# Terminology {#cha-terminology}


## Phenology {#output-phenology}

- **Plastochron** The plastochron is commonly used as the thermal time between the appearance of  successive leaf primordia on a shoot.
- **Phyllochron** The phyllochron is the thermal time it takes for successive leaves on a shoot to reach the same developmental stage.

## Structure {#output-structure}

- **Node (Phytomer)** A phytomer unit is defined as consisting of a leaf, and the associated axillary bud, node and internode.
- **Main stem** The first culm that emerges from the seeds is the main stem.
- **Tiller (Branch)** All remaining culms that emerges from main stem or other tillers (branches), are referred as tillers or branches.
- **Apex**  A shoot apex is the terminal bud of plants that grows from 0.1-1.0 mm and consists of the apical meristem, developing leaves and the immediate surrounding leaf primordial. Each tiller has an apex which continuously developes new leaf. 


## Leaf {#output-leaf}

- **Leaf organ** is only included leaf blades excluding section under sheath, i.e. only parts of leaf blades to produce photosynthate. 
- **Huan Index** is mainly concerned with the leaf production stage of development [@haun_visual_1973]. The length of each emerging leaf is expressed as a fraction of the length of the preceding fully emerged leaf. For example, a 3.2 indicates that three leaves are fully emerged, and a fourth leaf has emerged two-tenths of the length of the third.
